# This workflow sets up and runs MSBuild to build a Visual Studio solution.

name: Build

on:
  push:
    branches: 
      - github-actions

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Setup and run MSBuild

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup_msbuild
        
      - name: Run MSBuild
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\TheGame.sln
