# This workflow sets up MSBuild and builds the VS solution.

name: Build

on:
  push:
    branches: 
      - github-actions

jobs:

  setup-msbuild:
    runs-on: windows-latest
    name: Set up MSBuild into PATH to use later
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup-msbuild-path
  
  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild to build a VS solution
    needs: setup-msbuild
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: MSBuild
      run: msbuild TheGame.sln
