# This workflow sets up and runs MSBuild and VSTest to build and test a Visual Studio solution.

name: Build and Test

on:
  push:
    branches: 
      - master
      - test/*
      - feature/*
      - bugfix/*
  
  pull_request:
    branches:
      - master
      - test/*
      - feature/*
      - bugfix/*

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild and VSTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup_msbuild
        
      - name: Run MSBuild
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\TheGame.sln
        
      - name: Setup VSTest path
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Run VSTest
        id: run_vstest
        working-directory: ${{ github.workspace }}\x64\Debug\
        run: vstest.console.exe /Platform:x64 .\UnitTests.dll
