# This workflow sets up and runs MSBuild and VSTest to build and test a Visual Studio solution.

name: Build and Test

on:
  push:
    branches: 
      - github-actions

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild and VSTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup_msbuild
        
      - name: Run MSBuild
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\TheGame.sln
        
      - name: Find debug folder
        id: find_debug
        run: |
          pwd
          dir
        
      #- name: Find VSTest
      #  id: run_vstest
      #  run: |
      #    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\BuildTools\Common7\IDE\Extensions\TestPlatform\
      #    dir
          
# where I think tests are found: ${{ github.workspace }}\Debug\UnitTests.dll
