# This workflow sets up MSBuild and builds the VS solution.

name: Build

on:
  push:
    branches: 
      - github-actions

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Setup and run MSBuild

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup-msbuild-path
        
      - name: MSBuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\*.sln
