# This workflow sets up MSBuild and builds the VS solution.

name: Build

on:
  push:
    branches: 
      - github-actions

jobs:

  setup-msbuild:
    runs-on: windows-latest
    name: Set up MSBuild into PATH to use later

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        id: setup-msbuild-path
  
  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild to build a VS solution
    needs: setup-msbuild
    
    steps:
    - name: MSBuild
      id: msbuildPath
      run: msbuild -version
    
    - name: echo msbuild path
      run: echo "${{ steps.run-msbuild.outputs.msbuildPath }}"
