# This workflow sends a slack notification

name: slack-notification

on:
  issue_comment:
    types:
      - created
    branches:
      - test/*

jobs:
  slack-notification:
    runs-on: windows-latest
    name: Sends a message to Slack when an issue is made.
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-text: Hello! Something is burning! Or not...
          slack-optional-icon_emoji: ":fire:"
          slack-optional-as_user: false
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
