# This workflow sets up MSBuild and VSTest everytime commits are pushed to master, feature or test branches.

name: setup-build-test

on:
  push:
    branches: 
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  notify-slack-start:
    runs-on: windows-latest
    name: Notify Slack of workflow starting
    
    steps:
      - name: Notify Slack
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "`${{ github.event_name }}` on `${{ github.ref }}` triggered `${{ github.workflow }}`"

  setup-msbuild:
    runs-on: windows-latest
    name: Helps set up MSBuild into PATH for later usage
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1
        id: setup-msbuild-path

      - name: Send message to Slack with outcome of this job.
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "${{ github.job }} - ${{ job.status }}"

  setup-vstest:
    runs-on: windows-latest
    name: Helps set up VSTest into Path for later usage
    
    steps:
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
        id: setup-vstest-path
        
      - name: Run VSTest
        id: run-VSTest
        run: vstest.console.exe /Platform:x64 .\test\CustomMayd.Services.Serialization.Tests\AppxPackages\CustomMayd.Services.Serialization.Tests_1.0.0.0_Debug_Test\CustomMayd.Services.Serialization.Tests_1.0.0.0_x86_Debug.appx

      - name: Send message to Slack with outcome of this job.
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "${{ github.job }} - ${{ job.status }}"
  
  notify-slack-end:
    runs-on: windows-latest
    name: Sends a Slack notification with the outcome of the workflow on completion.
    needs: [ notify-slack-start, setup-msbuild, setup-vstest ]

    steps:
      - name: Notify Slack of workflow completing
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-text: "Workflow `${{ github.workflow }}` complete! :tada: Outcome: "
