# This workflow sets up MSBuild and VSTest everytime commits are pushed to master, feature or test branches.

name: Setup - Build - Test

on:
  push:
    branches: 
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  
  notify-slack-start:
    runs-on: windows-latest
    name: Notify Slack of workflow starting
    
    steps:
      - name: Send message to Slack
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "New `${{ github.event_name }}` on `${{ github.ref }}` triggered `${{ github.workflow }}`!"

  setup-msbuild:
    runs-on: windows-latest
    name: Set up MSBuild into PATH to use later

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1
        id: setup-msbuild-path

      - name: Send message to Slack with outcome of this job
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: ":heavy_check_mark: `${{ github.job }}` complete"
  
  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild to build a VS solution
    needs: setup-msbuild
    defaults:
      run:
        shell: cmd

    steps:
      - name: Run MSBuild to build the VS solution
        run: echo msbuild.exe /github/workspace/TheGame.sln
        
      - name: Send message to Slack with outcome job
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: ":heavy_check_mark: `${{ github.job }}` complete"

  setup-vstest:
    runs-on: windows-latest
    name: Set up VSTest into Path to use later

    steps:
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
        id: setup-vstest-path

      - name: Send message to Slack with outcome job
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: ":heavy_check_mark: `${{ github.job }}` complete"

  run-vstest:
    runs-on: windows-latest
    name: Run VSTest to run the VS unit tests
    needs: [ setup-vstest, run-msbuild ]
    defaults:
      run:
        shell: cmd
    
    steps:
        - name: Run VSTest
          id: run-VSTest
          run: echo vstest.console.exe /github/workspace/TheGame/Debug/UnitTests.dll
          continue-on-error: true
          
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT" 
    
        - name: Send message to Slack with outcome job
          uses: archive/github-actions-slack@v1.0.0
          with:
            slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
            slack-channel: github
            slack-optional-icon_emoji: ":nerd_face:"
            slack-text: ":heavy_check_mark: `${{ github.job }}` complete"

  notify-slack-end:
    runs-on: windows-latest
    name: Notify Slack of workflow completion
    needs: [ notify-slack-start, setup-msbuild, run-msbuild, setup-vstest, run-vstest ]

    steps:
      - name: Send message to Slack
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "Workflow `${{ github.workflow }}` complete! :tada:"
