# This workflow sets up MSBuild and VSTest everytime commits are pushed to master, feature or test branches.

name: setup-build-test

on:
  push:
    branches: 
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  notify-slack-start:
    runs-on: windows-latest
    name: Notify Slack of workflow starting
    
    steps:
      - name: Send message to Slack
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "New `${{ github.event_name }}` on `${{ github.ref }}` triggered `${{ github.workflow }}`!"

  setup-msbuild:
    runs-on: windows-latest
    name: Set up MSBuild into PATH to use later
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout-code
        
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1
        id: setup-msbuild-path

      - name: Send message to Slack with outcome of this job
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "- `${{ github.job }}` complete :heavy_check_mark:"
  
  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild to build a VS solution
    
    steps:
      - name: Run MSBuild to build the VS solution
        run: echo msbuild.exe /github/workspace/TheGame.sln
        
      - name: Send message to Slack with outcome of this job
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "- `${{ github.job }}` complete :heavy_check_mark:"

#  setup-vstest:
#    runs-on: windows-latest
#    name: Set up VSTest into Path to use later
#    
#    steps:
#      - name: Setup VSTest Path
#        uses: darenm/Setup-VSTest@v1
#        id: setup-vstest-path
#        
#      - name: Setup NuGet
#        uses: NuGet/setup-nuget@v1.0.2
#        
#      - name: Debug Build UWP app
#        run: msbuild .\dev\CustomMayd.Services.Serialization\CustomMayd.Services.Serialization.sln /p:Configuration=Debug /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxPackageDir=".\AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
#        
#      - name: Run VSTest
#        id: run-VSTest
#        run: vstest.console.exe /Platform:x64 .\test\CustomMayd.Services.Serialization.Tests\AppxPackages\CustomMayd.Services.Serialization.Tests_1.0.0.0_Debug_Test\CustomMayd.Services.Serialization.Tests_1.0.0.0_x86_Debug.appx
#
#      - name: Send message to Slack with outcome of this job
#        uses: archive/github-actions-slack@v1.0.0
#        with:
#          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
#          slack-channel: github
#          slack-optional-icon_emoji: ":nerd_face:"
#          slack-text: ":heavy_check_mark: `${{ github.job }}` complete"

  notify-slack-end:
    runs-on: windows-latest
    name: Notify Slack of workflow completion
    needs: [ notify-slack-start, setup-msbuild, run-msbuild ]

    steps:
      - name: Send message to Slack
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: github
          slack-optional-icon_emoji: ":nerd_face:"
          slack-text: "Workflow `${{ github.workflow }}` complete! :tada:"
